version: '3.9'
services:
  db:
    container_name: quotes-db-21bcp312
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quotesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  api:
    container_name: quotes-api-21bcp312
    build: ./api
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: quotesdb
    ports:
      - "5001:5001"
  app:
    container_name: quotes-frontend-21bcp312
    build: ./app
    depends_on:
      - api
    ports:
      - "5002:5002"
volumes:
  db-data:
